/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyApp;


public class App {
    public String ConsoleMenu() {
        return "Console-Application: Exercise-1               <Mohamed Neji> <Ghazouani> <579181>\n" +
                " 1. Greatest Common Divisor (GCD) - (Recursive) Euclid's algorithm subtraction.\n" +
                " 2. Greatest Common Divisor (GCD) - (Iterative) Euclid's algorithm subtraction.\n" +
                " 3. Greatest Common Divisor (GCD) - (Recursive) Euclid's algorithm division rest.\n" +
                " 4. Greatest Common Divisor (GCD) - (Iterative) Euclid's algorithm division rest.\n" +
                " 5. Sieve of Eratosthenes.\n" +
                " 6. Search for a specific string in Linus Torvald's joke (String-MatchingAlgorithm).\n" +
                " 0. Exit.\n" +
                " Please enter a number for an option:";
    }

    public static void main(String[] args) {
        System.out.println(new App().ConsoleMenu());
    }
}
